# -*- coding: utf-8 -*-
"""Amazon Web Scraper Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IZAmyLKLfmfhZ2yK3zKM-cL1yMqwwMVl
"""

# import libraries
from bs4 import BeautifulSoup
import requests
import time
import datetime
import smtplib

# Connect to Website and pull in data
URL = 'https://www.amazon.com/Garmin-Instinct-Features-Monitoring-Graphite/dp/B07HYX9P88/ref=sr_1_6?_encoding=UTF8&content-id=amzn1.sym.33f8f65b-b95c-44af-8b89-e59e69e79828&dib=eyJ2IjoiMSJ9.NhtP_3cV6I_AC3iGgzwjz3mm7vCKzPQXuUWDplhsSchYMkAuSYG9rc84igR3ylC7_2pq4lqS-Tk-9cBTDvrjNdrzHOIsEu-a3iA4VNL6RI80KKm7oxpQ9QyxvbxlV1q45AAk0_CFvVsaiaw8knKnVopa0xWjivhdBN9LmbPagWomL615mAea1fbDZV0wn0hLWc_ZF4ZLWyL28iQUb4RvnovcR0e-B8RzSZtLBLTgbMU.A6MExndoDv-98oDAb8gROIO7Do-1lbjdK40lJn7rFRE&dib_tag=se&keywords=activity%2Btrackers%2Band%2Bsmartwatches&pd_rd_r=1405bddc-ac4e-46e9-a857-dd89dda8fabf&pd_rd_w=mbw59&pd_rd_wg=gBgLl&pf_rd_p=33f8f65b-b95c-44af-8b89-e59e69e79828&pf_rd_r=JDDWRKGGCK3YKT303F3N&qid=1709200003&sr=8-6&th=1'
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
    "Accept-Encoding": "gzip, deflate",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "DNT": "1",
    "Connection": "close",
    "Upgrade-Insecure-Requests": "1"
}  # Set headers to mimic a browser's request
page = requests.get(URL, headers=headers)  # Send HTTP request to the URL
soup1 = BeautifulSoup(page.content, "html.parser")  # Parse the HTML content of the page
soup2 = BeautifulSoup(soup1.prettify(), "html.parser")  # Make the HTML content more readable

# Extract title and price from the page
title = soup2.find(id='productTitle').get_text()  # Find the product title
price = soup2.find(class_='a-offscreen').get_text()  # Find the product price

print(title)
print(price)

# Clean up the data
price = price.strip()[1:]  # Remove leading and trailing spaces and currency symbol
title = title.strip()  # Remove leading and trailing spaces
print(title)
print(price)

# Create a Timestamp for your output to track when data was collected
import datetime
today = datetime.date.today()  # Get today's date
print(today)

# Create CSV and write headers and data into the file
import csv
header = ['Title', 'Price', 'Date']  # Define CSV header
data = [title, price, today]  # Define CSV data
with open('AmazonWebScraperDataset.csv', 'w', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(header)  # Write header to CSV
    writer.writerow(data)  # Write data to CSV

import pandas as pd
df = pd.read_csv(r'/content/AmazonWebScraperDataset.csv')  # Read CSV data into a DataFrame
print(df)

# Append data to the CSV
with open('AmazonWebScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)  # Append data to the CSV

#Combine all of the above code into one function


def check_price():
    URL = 'https://www.amazon.com/Garmin-Instinct-Features-Monitoring-Graphite/dp/B07HYX9P88/ref=sr_1_6?_encoding=UTF8&content-id=amzn1.sym.33f8f65b-b95c-44af-8b89-e59e69e79828&dib=eyJ2IjoiMSJ9.NhtP_3cV6I_AC3iGgzwjz3mm7vCKzPQXuUWDplhsSchYMkAuSYG9rc84igR3ylC7_2pq4lqS-Tk-9cBTDvrjNdrzHOIsEu-a3iA4VNL6RI80KKm7oxpQ9QyxvbxlV1q45AAk0_CFvVsaiaw8knKnVopa0xWjivhdBN9LmbPagWomL615mAea1fbDZV0wn0hLWc_ZF4ZLWyL28iQUb4RvnovcR0e-B8RzSZtLBLTgbMU.A6MExndoDv-98oDAb8gROIO7Do-1lbjdK40lJn7rFRE&dib_tag=se&keywords=activity%2Btrackers%2Band%2Bsmartwatches&pd_rd_r=1405bddc-ac4e-46e9-a857-dd89dda8fabf&pd_rd_w=mbw59&pd_rd_wg=gBgLl&pf_rd_p=33f8f65b-b95c-44af-8b89-e59e69e79828&pf_rd_r=JDDWRKGGCK3YKT303F3N&qid=1709200003&sr=8-6&th=1'

    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

    page = requests.get(URL, headers=headers)

    soup1 = BeautifulSoup(page.content, "html.parser")

    soup2 = BeautifulSoup(soup1.prettify(), "html.parser")

    title = soup2.find(id='productTitle').get_text()

    price = soup2.find(class_='a-offscreen').get_text()

    price = price.strip()[1:]
    title = title.strip()

    import datetime

    today = datetime.date.today()

    import csv

    header = ['Title', 'Price', 'Date']
    data = [title, price, today]

    with open('AmazonWebScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

# Runs check_price after a set time and inputs data into your CSV
while True:
    check_price()  # Call the check_price function
    time.sleep(5)  # Sleep for 5 seconds before running again

import pandas as pd
df = pd.read_csv(r'/content/AmazonWebScraperDataset.csv')
print(df)

# If uou want to try sending yourself an email (just for fun) when a price hits below a certain level you can try it
# out with this script

def send_mail():
    server = smtplib.SMTP_SSL('smtp.gmail.com',465)
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login('xxxxxxxx@gmail.com','xxxxxxxxxx')

    subject = "Hurry up and check now! The smartwatch you're interested in is priced below $170."
    body = "Atip, Don't miss out on this thrilling opportunity! It's finally here—the moment you've been waiting for to snag the smartwatch of your dreams. Seize it now! Link here: https://www.amazon.com/Garmin-Instinct-Features-Monitoring-Graphite/dp/B07HYX9P88/ref=sr_1_6?_encoding=UTF8&content-id=amzn1.sym.33f8f65b-b95c-44af-8b89-e59e69e79828&dib=eyJ2IjoiMSJ9.NhtP_3cV6I_AC3iGgzwjz3mm7vCKzPQXuUWDplhsSchYMkAuSYG9rc84igR3ylC7_2pq4lqS-Tk-9cBTDvrjNdrzHOIsEu-a3iA4VNL6RI80KKm7oxpQ9QyxvbxlV1q45AAk0_CFvVsaiaw8knKnVopa0xWjivhdBN9LmbPagWomL615mAea1fbDZV0wn0hLWc_ZF4ZLWyL28iQUb4RvnovcR0e-B8RzSZtLBLTgbMU.A6MExndoDv-98oDAb8gROIO7Do-1lbjdK40lJn7rFRE&dib_tag=se&keywords=activity%2Btrackers%2Band%2Bsmartwatches&pd_rd_r=1405bddc-ac4e-46e9-a857-dd89dda8fabf&pd_rd_w=mbw59&pd_rd_wg=gBgLl&pf_rd_p=33f8f65b-b95c-44af-8b89-e59e69e79828&pf_rd_r=JDDWRKGGCK3YKT303F3N&qid=1709200003&sr=8-6&th=1"

    msg = f"Subject: {subject}\n\n{body}"

    server.sendmail(
        'xxxxxxxxx@gmail.com',
        msg

    )